name: Continuous Integration

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      XF_API_URL: ${{ secrets.XF_API_URL }}
      XF_API_KEY: ${{ secrets.XF_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: ${{ env.DB_PORT }}
          mysql database: ${{ env.DB_DATABASE }}
          mysql user: ${{ env.DB_USERNAME }}
          mysql password: ${{ env.DB_PASSWORD }}

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug,pdo_mysql

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Initialize Laravel application
        run: |
          composer run-script post-root-package-install
          composer run-script post-create-project-cmd

      - name: Run PHPUnit Tests
        env:
          XDEBUG_MODE: coverage
        run: php artisan test --coverage-clover="./coverage.xml" --testdox

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
